### ISSUE TITLE
getconsumption gives void answer from api

### ISSUE THREAD

**Issue by martintamke** [EnergieID/smappy#20]
Thanks a lot for this handy tool. I have been using the localsmappy part quite extensively. 

I hope you can have a look at the code again, as accessing consumption data from the web smappee API does not work properly (anymore?).
I can authenticate successfully and use Epoch Timestamps as entries for the _getConsumption command.
e.g.:
`start = 1503213249`
`end = 1503731649`
`s.get_consumption(service_location_id=service_location_id, start=start, end=end, aggregation=3)`

This results in an asnwer from the Smappee API like this:
`{u'consumptions': [], u'serviceLocationId': 19938}`

I would expect an outcome similar to the one in your example on the wiki [https://github.com/EnergieID/smappy/wiki](url) . 
It would be great, if you could have a look. thanks

**Comment by JrtPec** [comment]
The Smappee API takes milliseconds sinds epoch as input, not seconds. If you input a datetime object to Smappy, the conversion is done for you, but if you input an int it just passes it along without checking. So you should've used `start = 1503213249000` and `end = 1503731649000`.

This info is missing from the docstrings, so I'll add it there.

**Comment by martintamke** [comment]
Thanks @JrtPec  for the swift answer - yes, that is, what I tried at first. However I get an error message, which points at the part of the smappy code, where milliseconds are automatically added:
```python
>>> s.get_consumption(service_location_id=service_location_id, start= 1503213249000, end=1503731649000, aggregation=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-armv7l/egg/smappy/smappy.py", line 28, in wrapper
  File "build/bdist.linux-armv7l/egg/smappy/smappy.py", line 197, in get_consumption
  File "build/bdist.linux-armv7l/egg/smappy/smappy.py", line 245, in _get_consumption
  File "build/bdist.linux-armv7l/egg/smappy/smappy.py", line 446, in _to_milliseconds
NotImplementedError: Time format not supported. Use epochs,                                        Datetime or Pandas Datetime
```

the same error comes up, when I use the datetime format and led the code convert:
```python
>>> s.get_consumption(service_location_id=service_location_id, start='2017-08-20 16:55:25.063857', end='2017-08-27 16:56:28.457132', aggregation=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-armv7l/egg/smappy/smappy.py", line 28, in wrapper
  File "build/bdist.linux-armv7l/egg/smappy/smappy.py", line 197, in get_consumption
  File "build/bdist.linux-armv7l/egg/smappy/smappy.py", line 245, in _get_consumption
  File "build/bdist.linux-armv7l/egg/smappy/smappy.py", line 446, in _to_milliseconds
NotImplementedError: Time format not supported. Use epochs,                                        Datetime or Pandas Datetime
```

only when I use epoch timestamp without the miliseconds I receive an answer from the smappee API (even if it is a void one :-) )
```python
>>> s.get_consumption(service_location_id=service_location_id, start=1503213249, end=150373164, aggregation=3)
{u'consumptions': [], u'serviceLocationId': 19938}
```

I assume I do some very stupid mistake.....

**Comment by JrtPec** [comment]
Wow, this is something I haven't seen before.

First let's get this out of the way: there is no bug in your second approach, because `'2017-08-20 16:55:25.063857'` is a string, not a datetime object.

So about the first try:
The method `_to_milliseconds` should return after the line `isinstance(time, int)`. So it seems like your Python installation is evaluating `1503213249000` as something else than an int.
Could you try `isinstance(1503213249000, int)` in a console? Does it evaluate to `False`?

I found [this reference](https://books.google.be/books?id=Chr1NDlUcI8C&pg=PA38&lpg=PA38&dq=python+linux+isinstance+int+returns+false&source=bl&ots=ODAyynhXHo&sig=qqv-FXi5-uFxBTz_wIueRek3otg&hl=nl&sa=X&ved=0ahUKEwirjLm13PfVAhXHJlAKHYE8CL0Q6AEIXjAH#v=onepage&q=python%20linux%20isinstance%20int%20returns%20false&f=false): 

> In Python 2, the expression `isinstance(x, int)` will return `False` if `x` is an integer that has been promoted to a long.

I tried it on my Python 2 installation and `isinstance(1503213249000000000, int)` was still `True`, but `isinstance(15032132490000000000, int)` was suddenly `False`.

So you could get rid of the problem by using Python 3 (hint hint).

Replacing that line with `isinstance(time, (int, float, long))`, should fix it though.
Can you try `isinstance(1503213249000,(int, float, long))`?

**Comment by JrtPec** [comment]
Since the `long` type no longer exists in Python 3, I have fixed it like this:

```python
import numbers
isinstance(x, numbers.Number)
```
That should cover all bases.

I pushed it in https://github.com/EnergieID/smappy/commit/053e9b3bee082085b16c7f357e0f119d5b9e6a13 and it is on PyPi in Smappy version 0.2.12

**Comment by martintamke** [comment]
hi @JrtPec 
thx - I had in deed Python 2.7 running here updating now ... will report how it works in Python3.... 
;-)

**Comment by martintamke** [comment]
Hi @JrtPec 
after installation of python3, panda etc: I can confirm that the problem was with me using python2.7. It shows indeed ´isinstance(15032132490000000000, int)´ as ´False´.

I checked: and all is fine, when run in python3:
```python
 >>> isinstance(1503213249000000000, int)
True
>>> isinstance(15032132490000000000, int)
True
```
using epoch values without miliseconds produces as expected an void answer
```python
>>> s.get_consumption(service_location_id=service_location_id, start=1503213249, end=150373164, aggregation=3)
{'consumptions': [], 'serviceLocationId': 19938}
```

using correct epoch format is successful
```python
>>> s.get_consumption(service_location_id=service_location_id, start= 1503213249000, end=1503731649000, aggregation=3)
{'consumptions': [{'timestamp': 1503266400000, 'solar': 0.0, .......
```

thanks for swift reply -- now I can start my project :smile:
