### ISSUE TITLE
Server Error when get consumption api

### ISSUE THREAD

**Issue by alexfqc** [EnergieID/smappy#21]
I am using node to get the api and I got the token and the servicelocations via api, but when I try to use the consumption api I got the server error.

I am using node-fetch and the function:

```
const getConsumption = ({ token, id }) => {
  fetch(`https://app1pub.smappee.net/dev/v1/servicelocation/${id}/consumption`, {
    method: 'GET',
    body: 'aggregation=3&from=1388534400000&to=1391212800000',
    headers: {
      'Authorization': `Bearer ${token}`,
    }
  })
  .catch(function(error) {
    console.log(error);
  })
  .then(function(res) {
    console.log(res);
    return res.json();
  }).then(function(json) {
      console.log(json);
  });
};
```

**Comment by JrtPec** [comment]
What is the error that you're getting? It might give you a clue as to what is wrong.

I notice that you are requesting timestamps in the year 2014. Smappee doesn't serve daily data that far in the past, so it might work if you change your timestamps to something more recent.

**Comment by alexfqc** [comment]
My error is: FetchError: 
`invalid json response body at https://app1pub.smappee.net/dev/v1/servicelocation/25058/consumption reason: Unexpected token < in JSON at position 0`

**Comment by JrtPec** [comment]
Seems to me like you're not receiving a JSON response at all, but HTML (that's why it thinks "<" is an invalid character).

Can you print the raw server response, without treating it as JSON?

**Comment by alexfqc** [comment]
I've got the response switching fetch for axios.

Thanks for helpping me.
