### ISSUE TITLE
Always on consumption mismatch

### ISSUE THREAD

**Issue by GadgetUK** [EnergieID/smappy#24]
Figures returned by the API don't match those reported in the my.smapee interface for 'always on'

>>> start = end - dt.timedelta(days=1)
>>> s.get_consumption(service_location_id=service_location_id, start=start, end=end, aggregation=3)
{'consumptions': [{'solar': 4555.2, 'consumption': 12436.6, 'timestamp': 1516320000000, 'alwaysOn': 91195.0}], 'serviceLocationId': 20917}
>>> 

![image](https://user-images.githubusercontent.com/1688999/35177069-dbc4f914-fd74-11e7-81cf-1a010e5a11f5.png)

**Comment by JrtPec** [comment]
I've received this complaint before, but I'm afraid there's not a lot that can be done about it from this site.
The data returned by Smappy is taken directly from the Smappee API and is not altered in any way.

You could contact Smappee directly.

**Comment by GadgetUK** [comment]
I've had a response back, which might be worth documenting

"API reports the values in Wh. 
1kWh = 1000 Wh. So that means 4555,2 Wh equals 4,56 kWh. Same for solar values. 
For the alwaysON value we use another value. in the graphical view in the app it shows the value in kWh. The API reports the value as W per 5 minutes. In order to get the value in kWh you will first have to change the value to kW. So from W per 5 minutes to KW = devided by 12. So 91195/12. That's 7599,5. Then devide by 1000 to change from kW to kWh. 7599,5/1000 = 7,59 kWh. "

**Comment by JrtPec** [comment]
Okay...

The code can easily be adapted to handle this.

The only question is: do I make reporting consumption in Wh the default? I think it should be, but if I add it right now, some people's older code might not work well anymore.
I could also keep the current behaviour as default, and add the conversion with a flag of some sort, so it will not break any existing code.

What do you think?

**Comment by martintamke** [comment]
@GadgetUK  - thanks for getting this info  - it took me quite a while to find the conversion out myself. ...

@JrtPec  Changing the code would definitely disturb existing users. A flag is however a crooked solution.: new users would wonder, why they have to set it. An idea would be to have in an updated version Wh as default - and use a flag to have Legacy behaviour?

**Comment by JrtPec** [comment]
@martintamke I think it is best to have Wh as default: the methods are called `get_consumption` and the like, it implies that the values returned are in Wh. The behaviour we have right now is therefore a "bug". I will add a flag `raw` though, so you are able to still get the unprocessed data from the api.

Exisiting users will have to suck it up: stick with an older version of the code, or update to the version with the "bugfix". This is why we use version numbers like 0.X, it means things are still in development and are prone to change. Once we are 100% confident that everything is working well we can progress to version 1.X.

**Comment by JrtPec** [comment]
@GadgetUK @martintamke I have created a pull request, see #25.
Please let me know if you have any issues with this approach.
